// A sheet that does not arrive must say so.
//
// Phaser's answer to a failed texture load is to hand out a 32x32 magenta-and-black `__MISSING`
// checkerboard and carry on rendering. The game looks like it is working and draws black squares,
// which is exactly what happened on GitHub Pages and took a browser-specific bug report to
// notice. Nothing in the engine reported it, because nothing was listening.
//
// This matters more the more sheets there are: they are generated by `tools/build-*.js` from art
// that lives outside this repository, so "a sheet is missing, misnamed or half-built" is the most
// likely thing to go wrong as the tileset grows.

import { expect, test } from '@playwright/test';

const SEED = 'tiles-demo';

test('a sheet that fails to load is reported, not silently replaced', async ({ page }) => {
  const errors: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text());
  });

  // Block exactly one sheet. Everything else loads, so the game still boots and renders —
  // which is the point: this is the failure that hides, not one that crashes.
  await page.route('**/terrain*.png', (route) => route.abort());

  await page.goto(`?seed=${SEED}`);
  await expect(page.locator('.map-surface canvas')).toBeVisible({ timeout: 20_000 });
  await page.waitForTimeout(1500);

  const complaint = errors.find((text) => text.includes('[tiles]') && text.includes('terrain'));
  expect(complaint, `no load failure was reported. Console said: ${JSON.stringify(errors)}`)
    .toBeTruthy();
  // The message has to carry enough to act on: which sheet, and where it was looked for.
  expect(complaint).toContain('failed to load');

  const missing = await page.evaluate(() => (window as unknown as {
    __missingSheets?: () => readonly string[];
  }).__missingSheets?.() ?? null);
  if (missing !== null) expect(missing).toContain('terrain');
});

test('with every sheet present, nothing is reported missing', async ({ page }) => {
  const errors: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text());
  });

  await page.goto(`?seed=${SEED}`);
  await expect(page.locator('.map-surface canvas')).toBeVisible({ timeout: 20_000 });
  await page.waitForTimeout(1500);

  // Guards the guard: if this ever fires on a healthy build, the check above is meaningless.
  expect(errors.filter((text) => text.includes('[tiles]'))).toEqual([]);
});
